--
-- PostgreSQL database dump
--

\restrict rvDruGNs5RTpqoUsMfGfYx6YTeKpbz6CpjWhHo8XgfNhuthwwQxcL5XVwh78IKN

-- Dumped from database version 15.19
-- Dumped by pg_dump version 15.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Articles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Articles" (
    "Id" integer NOT NULL,
    "ArticleNumber" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Articles" OWNER TO postgres;

--
-- Name: Articles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Articles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Articles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Customers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Phone" text NOT NULL,
    "Balance" numeric NOT NULL,
    "Region" text DEFAULT ''::text NOT NULL,
    "Description" text
);


ALTER TABLE public."Customers" OWNER TO postgres;

--
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Expenses" (
    "Id" integer NOT NULL,
    "Category" text NOT NULL,
    "Amount" numeric NOT NULL,
    "Notes" text NOT NULL,
    "Date" timestamp with time zone NOT NULL
);


ALTER TABLE public."Expenses" OWNER TO postgres;

--
-- Name: Expenses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Expenses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Expenses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Payments" (
    "Id" integer NOT NULL,
    "CustomerId" text NOT NULL,
    "Customer" text NOT NULL,
    "Amount" numeric NOT NULL,
    "Date" timestamp with time zone NOT NULL
);


ALTER TABLE public."Payments" OWNER TO postgres;

--
-- Name: ProductPriceHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductPriceHistories" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "PricePunjab" numeric NOT NULL,
    "PriceSindh" numeric NOT NULL,
    "EffectiveFrom" timestamp with time zone NOT NULL,
    "Reason" text NOT NULL
);


ALTER TABLE public."ProductPriceHistories" OWNER TO postgres;

--
-- Name: ProductPriceHistories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductPriceHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductPriceHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Model" text NOT NULL,
    "Size" text NOT NULL,
    "Color" text NOT NULL,
    "Qty" integer NOT NULL,
    price_sindh numeric NOT NULL,
    price_punjab numeric DEFAULT 0.0 NOT NULL,
    "ArticleNumber" text DEFAULT ''::text NOT NULL,
    "ArticleId" integer
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sales" (
    "Id" integer NOT NULL,
    "CustomerId" text NOT NULL,
    "Customer" text NOT NULL,
    "Region" text NOT NULL,
    "Total" numeric NOT NULL,
    "RawTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TransportCompany" text NOT NULL,
    "BuiltyNo" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "LineItemsJson" text NOT NULL
);


ALTER TABLE public."Sales" OWNER TO postgres;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WagePayments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WagePayments" (
    "Id" integer NOT NULL,
    "WorkerId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Notes" text NOT NULL
);


ALTER TABLE public."WagePayments" OWNER TO postgres;

--
-- Name: WagePayments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."WagePayments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WagePayments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Workers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Workers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Phone" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Workers" OWNER TO postgres;

--
-- Name: Workers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Workers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Workers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Payments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Articles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Articles" ("Id", "ArticleNumber", "CreatedAt") FROM stdin;
1	512	2026-09-12 05:49:31.644416-07
2	250	2026-09-12 05:49:31.678312-07
3	215	2026-09-12 05:49:31.682145-07
4	503	2026-09-12 05:49:31.683215-07
5	15	2026-09-12 05:49:31.684159-07
6	12	2026-09-12 05:49:31.685133-07
7	1234678	2026-09-12 05:49:31.686259-07
8	666	2026-09-12 05:49:31.687124-07
9	813	2026-09-12 05:49:31.687904-07
10	01	2026-09-12 05:49:31.688583-07
11	02	2026-09-12 05:49:31.689263-07
12	807(Box)	2026-09-12 05:49:31.690074-07
13	808(Box)	2026-09-12 05:49:31.6909-07
14	808(Theli)	2026-09-12 05:49:31.691631-07
15	807(Theli)	2026-09-12 05:49:31.692295-07
16	102(Rangeen)	2026-09-12 05:49:31.692934-07
17	103(Rangeen)	2026-09-12 05:49:31.69365-07
18	103(Black)	2026-09-12 05:49:31.694338-07
19	102(Black)	2026-09-12 05:49:31.69504-07
\.


--
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Customers" ("Id", "Name", "Phone", "Balance", "Region", "Description") FROM stdin;
1	Tanveer Usman Chappal Sukkur	CUST-2683	799557	Sindh	\N
3	Taimoor Khalid Chappal Sukkur	CUST-5421	246266	Sindh	\N
4	Nadeem Chappal Sukkur	CUST-4638	109768	Sindh	\N
5	Waseem Chappal Sukkur	CUST-6321	381116	Sindh	\N
6	Adeel Khursheed Chappal Sukkur	CUST-3701	315634	Sindh	\N
7	Pak Chappal Sukkur	CUST-6059	113236	Sindh	\N
8	Bhai Bhai Chappal Sukkur	CUST-6961	521930	Sindh	\N
9	Sahab Ji Chappal Sukkur	CUST-8341	147571	Sindh	\N
10	Babu Chappal Sukkur	CUST-5347	307496	Sindh	\N
11	Aqeel Chappal Sukkur	CUST-3102	13718	Sindh	\N
12	Golden Chappal Sukkur	CUST-8893	344273	Sindh	\N
13	Amaan Chappal Sukkur	CUST-3196	2460	Sindh	\N
14	Mehfooz Chappal Sukkur	CUST-2569	82028	Sindh	\N
15	Anas Chappal Sukkur	CUST-5884	70897	Sindh	\N
16	Lal Chan Chappal Sukkur	CUST-6525	234113	Sindh	\N
17	Tuba Badar Chappal Sukkur	CUST-7051	131862	Sindh	\N
18	Omais Chappal Sukkur	CUST-7401	55480	Sindh	\N
19	Ata Israr Chappal Sukkur	CUST-8952	70405	Sindh	\N
20	Sardar Chappal Sukkur	CUST-9607	140308	Sindh	\N
21	Krishna Chapal Ghotki	CUST-4332	78580	Sindh	\N
22	Chawla Chappal Ghotki	CUST-7624	227796	Sindh	\N
23	Sk Chappal Ghotki	CUST-3723	191116	Sindh	\N
24	Fine Chappal Ghotki	CUST-5564	327790	Sindh	\N
25	Shan Chappal Ghotki	CUST-8404	57937	Sindh	\N
26	Sakhi Chappal Ghotki	CUST-7578	222268	Sindh	\N
27	Suhag Chappal Ghotki	CUST-1411	1320	Sindh	\N
28	Harwani Chappal Ghotki	CUST-5976	130760	Sindh	\N
29	Taj Chappal Larkana	CUST-1665	506350	Sindh	\N
30	Smart Chappal Larkana	CUST-3902	273440	Sindh	\N
31	Abbassi Chappal Larkana	CUST-7813	23840	Sindh	\N
32	New Lucky Chappal Ghotki	CUST-4279	0	Sindh	\N
2	Marhaba Chappal Sukkur	CUST-9078	216447	Sindh	\N
\.


--
-- Data for Name: Expenses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Expenses" ("Id", "Category", "Amount", "Notes", "Date") FROM stdin;
\.


--
-- Data for Name: Payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Payments" ("Id", "CustomerId", "Customer", "Amount", "Date") FROM stdin;
\.


--
-- Data for Name: ProductPriceHistories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductPriceHistories" ("Id", "ProductId", "PricePunjab", "PriceSindh", "EffectiveFrom", "Reason") FROM stdin;
1	81	160	160	2026-09-12 06:07:51.100031-07	Product price updated
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Products" ("Id", "Model", "Size", "Color", "Qty", price_sindh, price_punjab, "ArticleNumber", "ArticleId") FROM stdin;
1	512	7/10	Mix	0	290	277		1
2	512	4/6	Mix	0	260	242		1
3	512	1/3	Mix	0	230	217		1
4	512	11/13	Mix	0	200	187		1
5	512	8/10	Mix	0	170	157		1
6	250	7/10	Mix	0	160	160		2
7	250	4/6	Mix	0	145	145		2
8	250	1/3	Mix	0	130	130		2
9	250	10/13	Mix	0	115	115		2
10	215	7/10	Mix	0	160	160		3
11	215	4/6	Mix	0	145	145		3
12	215	1/3	Mix	0	130	130		3
13	215	10/13	Mix	0	115	115		3
14	503	7/10	Mix	0	160	160		4
15	503	4/6	Mix	0	145	145		4
16	503	1/3	Mix	0	130	130		4
17	503	10/13	Mix	0	115	115		4
18	15	7/10	Mix	0	147	137		5
19	15	3/6	Mix	0	140	130		5
20	12	7/10	Mix	0	147	137		6
21	12	3/6	Mix	0	140	130		6
22	1234678	7/10	Mix	0	137	127		7
23	1234678	3/6	Mix	0	130	120		7
24	666	7/10	Mix	0	350	350		8
25	666	4/6	Mix	0	320	320		8
26	666	1/3	Mix	0	290	290		8
27	666	11/13	Mix	0	260	260		8
28	666	8/10	Mix	0	230	230		8
29	813	7/10	Mix	0	200	200		9
30	813	4/6	Mix	0	185	185		9
31	813	1/3	Mix	0	170	170		9
32	813	10/13	Mix	0	155	155		9
33	813	6/9	Mix	0	140	140		9
50	01	30/35	Mix	0	200	186		10
51	01	24/29	Mix	0	170	156		10
52	01	8/13	Mix	0	200	186		10
53	01	2/7	Mix	0	170	156		10
54	02	30/35	Mix	0	200	186		11
55	02	24/29	Mix	0	170	156		11
56	02	8/13	Mix	0	200	186		11
57	02	2/7	Mix	0	170	156		11
58	807(Box)	7/10	Mix	0	260	250		12
59	807(Box)	4/6	Mix	0	240	230		12
60	807(Box)	1/3	Mix	0	220	210		12
61	807(Box)	11/13	Mix	0	200	190		12
62	807(Box)	8/10	Mix	0	180	170		12
63	808(Box)	7/10	Mix	0	260	250		13
65	808(Box)	4/6	Mix	0	240	230		13
66	808(Box)	1/3	Mix	0	220	210		13
67	808(Box)	11/13	Mix	0	200	190		13
68	808(Box)	8/10	Mix	0	180	170		13
69	808(Theli)	7/10	Mix	0	250	250		14
70	808(Theli)	4/6	Mix	0	230	230		14
71	808(Theli)	1/3	Mix	0	210	210		14
72	808(Theli)	11/13	Mix	0	190	190		14
73	808(Theli)	8/10	Mix	0	170	170		14
74	807(Theli)	7/10	Mix	0	250	250		15
75	807(Theli)	4/6	Mix	0	230	230		15
76	807(Theli)	1/3	Mix	0	210	210		15
77	807(Theli)	11/13	Mix	0	190	190		15
78	807(Theli)	8/10	Mix	0	170	170		15
79	102(Rangeen)	6/9	Mix	0	180	180		16
80	102(Rangeen)	3/5	ix	0	170	170		16
82	102(Rangeen)	9/12	Mix	0	155	155		16
83	103(Rangeen)	6/9	Mix	0	180	180		17
84	103(Rangeen)	3/5	ix	0	170	170		17
85	103(Rangeen)	13/2	Mix	0	170	160		17
86	103(Rangeen)	9/12	Mix	0	155	155		17
87	103(Black)	6/9	black	0	170	170		18
88	103(Black)	3/5	black	0	160	160		18
89	103(Black)	13/2	black	0	150	150		18
90	103(Black)	9/12	black	0	145	145		18
91	102(Black)	6/9	black	0	170	170		19
92	102(Black)	3/5	black	0	160	160		19
93	102(Black)	13/2	black	0	150	150		19
94	102(Black)	9/12	black	0	145	145		19
81	102(Rangeen)	13/2	Mix	0	160	160	102(Rangeen)	16
\.


--
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sales" ("Id", "CustomerId", "Customer", "Region", "Total", "RawTotal", "Discount", "TransportCompany", "BuiltyNo", "Date", "LineItemsJson") FROM stdin;
5	CUST-3701	Adeel Khursheed Chappal Sukkur	Sindh	131400	131400	0	Haji Sardar Goods	4494	2026-09-13 17:00:00-07	[{"productId":14,"model":"503","size":"7/10","qty":"25","unitType":"dozens","pairs":300,"price":160,"grossAmount":48000,"discountPerPair":0,"discountAmount":0,"netAmount":48000,"description":"[Article No: 14] 503 (Size: 7/10) - 25 dozens (300 pairs) @ Rs. 160/pair"},{"productId":15,"model":"503","size":"4/6","qty":"10","unitType":"dozens","pairs":120,"price":145,"grossAmount":17400,"discountPerPair":0,"discountAmount":0,"netAmount":17400,"description":"[Article No: 15] 503 (Size: 4/6) - 10 dozens (120 pairs) @ Rs. 145/pair"},{"productId":16,"model":"503","size":"1/3","qty":"5","unitType":"dozens","pairs":60,"price":130,"grossAmount":7800,"discountPerPair":0,"discountAmount":0,"netAmount":7800,"description":"[Article No: 16] 503 (Size: 1/3) - 5 dozens (60 pairs) @ Rs. 130/pair"},{"productId":80,"model":"102(Rangeen)","size":"3/5","qty":"10","unitType":"dozens","pairs":120,"price":170,"grossAmount":20400,"discountPerPair":0,"discountAmount":0,"netAmount":20400,"description":"[Article No: 80] 102(Rangeen) (Size: 3/5) - 10 dozens (120 pairs) @ Rs. 170/pair"},{"productId":81,"model":"102(Rangeen)","size":"13/2","qty":"10","unitType":"dozens","pairs":120,"price":160,"grossAmount":19200,"discountPerPair":0,"discountAmount":0,"netAmount":19200,"description":"[Article No: 81] 102(Rangeen) (Size: 13/2) - 10 dozens (120 pairs) @ Rs. 160/pair"},{"productId":82,"model":"102(Rangeen)","size":"9/12","qty":"10","unitType":"dozens","pairs":120,"price":155,"grossAmount":18600,"discountPerPair":0,"discountAmount":0,"netAmount":18600,"description":"[Article No: 82] 102(Rangeen) (Size: 9/12) - 10 dozens (120 pairs) @ Rs. 155/pair"}]
6	CUST-6961	Bhai Bhai Chappal Sukkur	Sindh	86400	86400	0	Haji Sardar Goods	4476	2026-09-13 17:00:00-07	[{"productId":1,"model":"512","size":"7/10","qty":"10","unitType":"dozens","pairs":120,"price":290,"grossAmount":34800,"discountPerPair":0,"discountAmount":0,"netAmount":34800,"description":"[Article No: 1] 512 (Size: 7/10) - 10 dozens (120 pairs) @ Rs. 290/pair"},{"productId":2,"model":"512","size":"4/6","qty":"5","unitType":"dozens","pairs":60,"price":260,"grossAmount":15600,"discountPerPair":0,"discountAmount":0,"netAmount":15600,"description":"[Article No: 2] 512 (Size: 4/6) - 5 dozens (60 pairs) @ Rs. 260/pair"},{"productId":3,"model":"512","size":"1/3","qty":"5","unitType":"dozens","pairs":60,"price":230,"grossAmount":13800,"discountPerPair":0,"discountAmount":0,"netAmount":13800,"description":"[Article No: 3] 512 (Size: 1/3) - 5 dozens (60 pairs) @ Rs. 230/pair"},{"productId":4,"model":"512","size":"11/13","qty":"5","unitType":"dozens","pairs":60,"price":200,"grossAmount":12000,"discountPerPair":0,"discountAmount":0,"netAmount":12000,"description":"[Article No: 4] 512 (Size: 11/13) - 5 dozens (60 pairs) @ Rs. 200/pair"},{"productId":5,"model":"512","size":"8/10","qty":"5","unitType":"dozens","pairs":60,"price":170,"grossAmount":10200,"discountPerPair":0,"discountAmount":0,"netAmount":10200,"description":"[Article No: 5] 512 (Size: 8/10) - 5 dozens (60 pairs) @ Rs. 170/pair"}]
7	CUST-2683	Tanveer Usman Chappal Sukkur	Sindh	339480	339480	0	Awais AlKashif Goods, New Chaudhary Brothers	3889,12179	2026-09-13 17:00:00-07	[{"productId":14,"model":"503","size":"7/10","qty":"28","unitType":"dozens","pairs":336,"price":160,"grossAmount":53760,"discountPerPair":0,"discountAmount":0,"netAmount":53760,"description":"[Article No: 14] 503 (Size: 7/10) - 28 dozens (336 pairs) @ Rs. 160/pair"},{"productId":15,"model":"503","size":"4/6","qty":"14","unitType":"dozens","pairs":168,"price":145,"grossAmount":24360,"discountPerPair":0,"discountAmount":0,"netAmount":24360,"description":"[Article No: 15] 503 (Size: 4/6) - 14 dozens (168 pairs) @ Rs. 145/pair"},{"productId":16,"model":"503","size":"1/3","qty":"14","unitType":"dozens","pairs":168,"price":130,"grossAmount":21840,"discountPerPair":0,"discountAmount":0,"netAmount":21840,"description":"[Article No: 16] 503 (Size: 1/3) - 14 dozens (168 pairs) @ Rs. 130/pair"},{"productId":17,"model":"503","size":"10/13","qty":"14","unitType":"dozens","pairs":168,"price":115,"grossAmount":19320,"discountPerPair":0,"discountAmount":0,"netAmount":19320,"description":"[Article No: 17] 503 (Size: 10/13) - 14 dozens (168 pairs) @ Rs. 115/pair"},{"productId":79,"model":"102(Rangeen)","size":"6/9","qty":"25","unitType":"dozens","pairs":300,"price":180,"grossAmount":54000,"discountPerPair":0,"discountAmount":0,"netAmount":54000,"description":"[Article No: 79] 102(Rangeen) (Size: 6/9) - 25 dozens (300 pairs) @ Rs. 180/pair"},{"productId":80,"model":"102(Rangeen)","size":"3/5","qty":"15","unitType":"dozens","pairs":180,"price":170,"grossAmount":30600,"discountPerPair":0,"discountAmount":0,"netAmount":30600,"description":"[Article No: 80] 102(Rangeen) (Size: 3/5) - 15 dozens (180 pairs) @ Rs. 170/pair"},{"productId":81,"model":"102(Rangeen)","size":"13/2","qty":"15","unitType":"dozens","pairs":180,"price":160,"grossAmount":28800,"discountPerPair":0,"discountAmount":0,"netAmount":28800,"description":"[Article No: 81] 102(Rangeen) (Size: 13/2) - 15 dozens (180 pairs) @ Rs. 160/pair"},{"productId":91,"model":"102(Black)","size":"6/9","qty":"25","unitType":"dozens","pairs":300,"price":170,"grossAmount":51000,"discountPerPair":0,"discountAmount":0,"netAmount":51000,"description":"[Article No: 91] 102(Black) (Size: 6/9) - 25 dozens (300 pairs) @ Rs. 170/pair"},{"productId":92,"model":"102(Black)","size":"3/5","qty":"15","unitType":"dozens","pairs":180,"price":160,"grossAmount":28800,"discountPerPair":0,"discountAmount":0,"netAmount":28800,"description":"[Article No: 92] 102(Black) (Size: 3/5) - 15 dozens (180 pairs) @ Rs. 160/pair"},{"productId":93,"model":"102(Black)","size":"13/2","qty":"15","unitType":"dozens","pairs":180,"price":150,"grossAmount":27000,"discountPerPair":0,"discountAmount":0,"netAmount":27000,"description":"[Article No: 93] 102(Black) (Size: 13/2) - 15 dozens (180 pairs) @ Rs. 150/pair"}]
8	CUST-7624	Chawla Chappal Ghotki	Sindh	184080	184080	0	Haji Sardar Goods	2911	2026-09-13 17:00:00-07	[{"productId":91,"model":"102(Black)","size":"6/9","qty":"30","unitType":"dozens","pairs":360,"price":170,"grossAmount":61200,"discountPerPair":0,"discountAmount":0,"netAmount":61200,"description":"[Article No: 91] 102(Black) (Size: 6/9) - 30 dozens (360 pairs) @ Rs. 170/pair"},{"productId":92,"model":"102(Black)","size":"3/5","qty":"15","unitType":"dozens","pairs":180,"price":160,"grossAmount":28800,"discountPerPair":0,"discountAmount":0,"netAmount":28800,"description":"[Article No: 92] 102(Black) (Size: 3/5) - 15 dozens (180 pairs) @ Rs. 160/pair"},{"productId":93,"model":"102(Black)","size":"13/2","qty":"15","unitType":"dozens","pairs":180,"price":150,"grossAmount":27000,"discountPerPair":0,"discountAmount":0,"netAmount":27000,"description":"[Article No: 93] 102(Black) (Size: 13/2) - 15 dozens (180 pairs) @ Rs. 150/pair"},{"productId":94,"model":"102(Black)","size":"9/12","qty":"10","unitType":"dozens","pairs":120,"price":145,"grossAmount":17400,"discountPerPair":0,"discountAmount":0,"netAmount":17400,"description":"[Article No: 94] 102(Black) (Size: 9/12) - 10 dozens (120 pairs) @ Rs. 145/pair"},{"productId":74,"model":"807(Theli)","size":"7/10","qty":"5","unitType":"dozens","pairs":60,"price":250,"grossAmount":15000,"discountPerPair":0,"discountAmount":0,"netAmount":15000,"description":"[Article No: 74] 807(Theli) (Size: 7/10) - 5 dozens (60 pairs) @ Rs. 250/pair"},{"productId":75,"model":"807(Theli)","size":"4/6","qty":"3","unitType":"dozens","pairs":36,"price":230,"grossAmount":8280,"discountPerPair":0,"discountAmount":0,"netAmount":8280,"description":"[Article No: 75] 807(Theli) (Size: 4/6) - 3 dozens (36 pairs) @ Rs. 230/pair"},{"productId":76,"model":"807(Theli)","size":"1/3","qty":"3","unitType":"dozens","pairs":36,"price":210,"grossAmount":7560,"discountPerPair":0,"discountAmount":0,"netAmount":7560,"description":"[Article No: 76] 807(Theli) (Size: 1/3) - 3 dozens (36 pairs) @ Rs. 210/pair"},{"productId":77,"model":"807(Theli)","size":"11/13","qty":"3","unitType":"dozens","pairs":36,"price":190,"grossAmount":6840,"discountPerPair":0,"discountAmount":0,"netAmount":6840,"description":"[Article No: 77] 807(Theli) (Size: 11/13) - 3 dozens (36 pairs) @ Rs. 190/pair"},{"productId":29,"model":"813","size":"7/10","qty":"5","unitType":"dozens","pairs":60,"price":200,"grossAmount":12000,"discountPerPair":0,"discountAmount":0,"netAmount":12000,"description":"[Article No: 29] 813 (Size: 7/10) - 5 dozens (60 pairs) @ Rs. 200/pair"}]
9	CUST-8893	Golden Chappal Sukkur	Sindh	126300	126300	0	New Chaudhary Brothers 	12175	2026-09-13 17:00:00-07	[{"productId":14,"model":"503","size":"7/10","qty":"30","unitType":"dozens","pairs":360,"price":160,"grossAmount":57600,"discountPerPair":0,"discountAmount":0,"netAmount":57600,"description":"[Article No: 14] 503 (Size: 7/10) - 30 dozens (360 pairs) @ Rs. 160/pair"},{"productId":15,"model":"503","size":"4/6","qty":"10","unitType":"dozens","pairs":120,"price":145,"grossAmount":17400,"discountPerPair":0,"discountAmount":0,"netAmount":17400,"description":"[Article No: 15] 503 (Size: 4/6) - 10 dozens (120 pairs) @ Rs. 145/pair"},{"productId":16,"model":"503","size":"1/3","qty":"10","unitType":"dozens","pairs":120,"price":130,"grossAmount":15600,"discountPerPair":0,"discountAmount":0,"netAmount":15600,"description":"[Article No: 16] 503 (Size: 1/3) - 10 dozens (120 pairs) @ Rs. 130/pair"},{"productId":17,"model":"503","size":"10/13","qty":"5","unitType":"dozens","pairs":60,"price":115,"grossAmount":6900,"discountPerPair":0,"discountAmount":0,"netAmount":6900,"description":"[Article No: 17] 503 (Size: 10/13) - 5 dozens (60 pairs) @ Rs. 115/pair"},{"productId":10,"model":"215","size":"7/10","qty":"15","unitType":"dozens","pairs":180,"price":160,"grossAmount":28800,"discountPerPair":0,"discountAmount":0,"netAmount":28800,"description":"[Article No: 10] 215 (Size: 7/10) - 15 dozens (180 pairs) @ Rs. 160/pair"}]
10	CUST-4279	New Lucky Chappal Ghotki	Sindh	72000	72000	0	Super Azad Malik Goods	6564	2026-09-13 17:00:00-07	[{"productId":3,"model":"512","size":"1/3","qty":"10","unitType":"dozens","pairs":120,"price":230,"grossAmount":27600,"discountPerPair":0,"discountAmount":0,"netAmount":27600,"description":"[Article No: 3] 512 (Size: 1/3) - 10 dozens (120 pairs) @ Rs. 230/pair"},{"productId":5,"model":"512","size":"8/10","qty":"10","unitType":"dozens","pairs":120,"price":170,"grossAmount":20400,"discountPerPair":0,"discountAmount":0,"netAmount":20400,"description":"[Article No: 5] 512 (Size: 8/10) - 10 dozens (120 pairs) @ Rs. 170/pair"},{"productId":52,"model":"01","size":"8/13","qty":"10","unitType":"dozens","pairs":120,"price":200,"grossAmount":24000,"discountPerPair":0,"discountAmount":0,"netAmount":24000,"description":"[Article No: 52] 01 (Size: 8/13) - 10 dozens (120 pairs) @ Rs. 200/pair"}]
11	CUST-7578	Sakhi Chappal Ghotki	Sindh	172800	172800	0	Super Azad Malik Goods	6608	2026-09-13 17:00:00-07	[{"productId":91,"model":"102(Black)","size":"6/9","qty":"25","unitType":"dozens","pairs":300,"price":170,"grossAmount":51000,"discountPerPair":0,"discountAmount":0,"netAmount":51000,"description":"[Article No: 91] 102(Black) (Size: 6/9) - 25 dozens (300 pairs) @ Rs. 170/pair"},{"productId":92,"model":"102(Black)","size":"3/5","qty":"15","unitType":"dozens","pairs":180,"price":160,"grossAmount":28800,"discountPerPair":0,"discountAmount":0,"netAmount":28800,"description":"[Article No: 92] 102(Black) (Size: 3/5) - 15 dozens (180 pairs) @ Rs. 160/pair"},{"productId":93,"model":"102(Black)","size":"13/2","qty":"15","unitType":"dozens","pairs":180,"price":150,"grossAmount":27000,"discountPerPair":0,"discountAmount":0,"netAmount":27000,"description":"[Article No: 93] 102(Black) (Size: 13/2) - 15 dozens (180 pairs) @ Rs. 150/pair"},{"productId":94,"model":"102(Black)","size":"9/12","qty":"15","unitType":"dozens","pairs":180,"price":145,"grossAmount":26100,"discountPerPair":0,"discountAmount":0,"netAmount":26100,"description":"[Article No: 94] 102(Black) (Size: 9/12) - 15 dozens (180 pairs) @ Rs. 145/pair"},{"productId":79,"model":"102(Rangeen)","size":"6/9","qty":"5","unitType":"dozens","pairs":60,"price":180,"grossAmount":10800,"discountPerPair":0,"discountAmount":0,"netAmount":10800,"description":"[Article No: 79] 102(Rangeen) (Size: 6/9) - 5 dozens (60 pairs) @ Rs. 180/pair"},{"productId":80,"model":"102(Rangeen)","size":"3/5","qty":"5","unitType":"dozens","pairs":60,"price":170,"grossAmount":10200,"discountPerPair":0,"discountAmount":0,"netAmount":10200,"description":"[Article No: 80] 102(Rangeen) (Size: 3/5) - 5 dozens (60 pairs) @ Rs. 170/pair"},{"productId":81,"model":"102(Rangeen)","size":"13/2","qty":"5","unitType":"dozens","pairs":60,"price":160,"grossAmount":9600,"discountPerPair":0,"discountAmount":0,"netAmount":9600,"description":"[Article No: 81] 102(Rangeen) (Size: 13/2) - 5 dozens (60 pairs) @ Rs. 160/pair"},{"productId":82,"model":"102(Rangeen)","size":"9/12","qty":"5","unitType":"dozens","pairs":60,"price":155,"grossAmount":9300,"discountPerPair":0,"discountAmount":0,"netAmount":9300,"description":"[Article No: 82] 102(Rangeen) (Size: 9/12) - 5 dozens (60 pairs) @ Rs. 155/pair"}]
12	CUST-3701	Adeel Khursheed Chappal Sukkur	Sindh	58800	58800	0	Haji Sardar Goods	4485	2026-09-13 17:00:00-07	[{"productId":2,"model":"512","size":"4/6","qty":"10","unitType":"dozens","pairs":120,"price":260,"grossAmount":31200,"discountPerPair":0,"discountAmount":0,"netAmount":31200,"description":"[Article No: 2] 512 (Size: 4/6) - 10 dozens (120 pairs) @ Rs. 260/pair"},{"productId":3,"model":"512","size":"1/3","qty":"10","unitType":"dozens","pairs":120,"price":230,"grossAmount":27600,"discountPerPair":0,"discountAmount":0,"netAmount":27600,"description":"[Article No: 3] 512 (Size: 1/3) - 10 dozens (120 pairs) @ Rs. 230/pair"}]
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Username", "PasswordHash", "Role") FROM stdin;
1	admin	$2a$11$sktxq8TGNX6NlTEjXgrs5u.tNlBjYYTVNiMa81DIDwfCGGgnQ00hG	Admin
\.


--
-- Data for Name: WagePayments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."WagePayments" ("Id", "WorkerId", "Amount", "PaymentDate", "Notes") FROM stdin;
\.


--
-- Data for Name: Workers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Workers" ("Id", "Name", "Phone", "Role", "IsActive", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260902100103_InitialProductionSchema	8.0.8
20260902130008_AddUserTable	8.0.8
20260907075607_AddRegionalPricingColumns	8.0.8
20260911131630_AddRegionToCustomers	8.0.8
20260912120855_AddArticlePricingAndWages	8.0.8
20260912122702_AddParentArticles	8.0.8
20260912132106_AddCustomerDescription	8.0.8
\.


--
-- Name: Articles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Articles_Id_seq"', 19, true);


--
-- Name: Customers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Customers_Id_seq"', 32, true);


--
-- Name: Expenses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Expenses_Id_seq"', 1, false);


--
-- Name: ProductPriceHistories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductPriceHistories_Id_seq"', 1, true);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 94, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: WagePayments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WagePayments_Id_seq"', 1, false);


--
-- Name: Workers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Workers_Id_seq"', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- Name: sales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sales_id_seq', 12, true);


--
-- Name: Articles PK_Articles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Articles"
    ADD CONSTRAINT "PK_Articles" PRIMARY KEY ("Id");


--
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- Name: Expenses PK_Expenses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id");


--
-- Name: ProductPriceHistories PK_ProductPriceHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductPriceHistories"
    ADD CONSTRAINT "PK_ProductPriceHistories" PRIMARY KEY ("Id");


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: WagePayments PK_WagePayments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WagePayments"
    ADD CONSTRAINT "PK_WagePayments" PRIMARY KEY ("Id");


--
-- Name: Workers PK_Workers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Workers"
    ADD CONSTRAINT "PK_Workers" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT payments_pkey PRIMARY KEY ("Id");


--
-- Name: Sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT sales_pkey PRIMARY KEY ("Id");


--
-- Name: IX_Articles_ArticleNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Articles_ArticleNumber" ON public."Articles" USING btree ("ArticleNumber");


--
-- Name: IX_ProductPriceHistories_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductPriceHistories_ProductId" ON public."ProductPriceHistories" USING btree ("ProductId");


--
-- Name: IX_Products_ArticleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Products_ArticleId" ON public."Products" USING btree ("ArticleId");


--
-- Name: IX_WagePayments_WorkerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_WagePayments_WorkerId" ON public."WagePayments" USING btree ("WorkerId");


--
-- Name: ProductPriceHistories FK_ProductPriceHistories_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductPriceHistories"
    ADD CONSTRAINT "FK_ProductPriceHistories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- Name: Products FK_Products_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE SET NULL;


--
-- Name: WagePayments FK_WagePayments_Workers_WorkerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WagePayments"
    ADD CONSTRAINT "FK_WagePayments_Workers_WorkerId" FOREIGN KEY ("WorkerId") REFERENCES public."Workers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict rvDruGNs5RTpqoUsMfGfYx6YTeKpbz6CpjWhHo8XgfNhuthwwQxcL5XVwh78IKN

