directories:
  output: release
  buildResources: build
appId: com.plusevr.shoefactory
productName: PLUS EVR ERP
files:
  - filter:
      - electron/**/*
      - ShoeFactoryApi/wwwroot/**/*
      - package.json
win:
  target: nsis
nsis:
  shortcutName: PLUS EVR ERP
  createDesktopShortcut: true
  createStartMenuShortcut: true
  perMachine: false
electronVersion: 44.3.0
